name: HER-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy==1.23.5
      - matplotlib==3.10.1
      - seaborn==0.13.2
      - torch==2.2.2
      - torchaudio==2.2.2
      - torchvision==0.17.2
      - tensorboard==2.19.0
      - tensorboardx==2.6.2.2
      - gym==0.26.2
      - gymnasium==1.0.0
      - pygame==2.6.1
      - wandb==0.19.8
      - stable-baselines3==2.4.0
      - cleanrl==0.4.8
      - pandas==2.2.3
      - opencv-python==4.11.0.86
      - pyyaml==6.0.2
